# Generated by Django 5.0.1 on 2024-01-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_completion',
            name='Rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workshop_registration',
            name='Rating',
            field=models.IntegerField(),
        ),
    ]
